### ISSUE TITLE
Optic hanging

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/SR3_installation#10]
### TODO & checklist
- [X] Find piano & tungsten wires
- [X] Find winch system

6. Hang the mirror
- [X] The winch is set properly.
- [x] Wires (&Phi;0.2 piano wire) are cut and wiped with aceton./
- [x] The base of the mirror box is properly set./
- [x] The piano wires are fixed in the grooves on the winch drums.
- [ ] The piano wires are wired around more than once on the winch drums.
- [ ] Wires are at the grooves on the wire breakers.
- [ ] The wires around the mirror is parallel.
- [ ] The wires go through the grooves on the wire clamps.
- [ ] Mirror is not dirty./
- [ ] Some PEEK jigs at the upper side of the mirror are removed.

**References**
p.12 to 13 in https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument?docid=4756
p.17 to 27 in https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument?docid=3830

**Comment by YoshinoriFujii** [comment]
http://klog.icrr.u-tokyo.ac.jp/osl/?r=4819

> We started with the work table, mirror box and KOACH filter on the +Y side of the assembly frame from yesterday, with the foot end of the mirror box towards -Y.
> We removed the lid and cylinder from the mirror box.
> We removed the PEEK retaining cylinder and PEEK L-bracket from the top of the mirror box.
> `We installed the foot section of the mirror box` **_->locked??_**
> We stood the box up onto the trolley and fastened it down with the three custom screws.
> We moved the trolley to the center of the optical table and locked it.

> We removed the bar at ≈10 o'clock (looking in +Y) to allow the wires to be threaded.
> `We noticed that the optic was not being supported by the PEEK corners on the mirror box foot, so we relaxed the PEEK screws on the L-brackets on the inner lid, so that the optic was able to tip towards -Y at the top and settle onto the PEEK supports at the bottom.` **_-> what??_**
> We removed all the clamp pieces from the clamp blocks.
> `We threaded two 0.2 mm piano wires from the top winches, down through the holes in the clamp blocks, under the optic and back up.`  **_-> properly wiped?_**
> We tightened the wires slightly, located them in the notches in the prisms and then checked that they were properly routed under the optic (straight and 10 mm apart).
> `We set up two laser levels at 267 mm above the top surface of the trolley baseplate.`  **_-> where??_**
> We raised the SR3 until it was off the stops at the bottom and approximately vertical (but still not at the final height or pitch angle).
> We set up the optical lever on the chest of drawers at a distance of 3 m from the AR side (which is also the flat side). `To have the optic pitch down by 1/300 on the HR side (+Y), we need the return beam to come back 3000/300 = 20 mm high on the AR side (-Y). ` **_-> 10mm??_**
> We retightened the PEEK screws to keep the optic safe overnight.

**Comment by YoshinoriFujii** [comment]
http://gwwiki.icrr.u-tokyo.ac.jp/JGWwiki/KAGRA/Subgroups/VIS/TypeB/Minutes Report for week of 4/23

> We hung the optic and set its pitch. The winch system had a lot of slop in it but the technique of relaxing the wires by lifting the optic on the EQ stops was effective in getting consistent results.
> We tightened the clamps using a torque wrench, using settings of 5 N.m for the primary clamps and 20 N.m for the secondary.
> We hung the RM and set its pitch. The RM winches were a lot more consistent.
> `However when tightening the clamps, the wire on the +Y side broke at the bottom edge of primary clamp. The wire on the -Y held, so the RM dropped a few mm onto the trolley on the +Y side.`
> We raised the RM trolley to support the RM and left the optic hanging inside it overnight as a safety test.
>` We then reversed the usual installation procedure to remove the RM and get the mirror box around the optic. ` **_-> reversing would be dangerous! How do we use?_** 
>We used clamp pieces as spacers to bridge the gaps created by the fact that the optic had been raised 3 mm during hanging and could not safely be lowered. `We then cut the wires`, leaving the op
> Shoda-san made SRM model (Dropbox/Largefiles/Subsystems/VIS/Design/SR/Model/SRM-MetalMass_180426)
> 
> Shoda-san made 2D drawings of LBB ballast masses
> Hirata-san washed parts.
