### ISSUE TITLE
Align the optic in Pitch

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/SR3_installation#11]
### TODO & checklist
- [x] bring an oplev

7. Align the mirror
- [x] The distance between the wire clamps on the IM and the wire breakers are the same at the both side. (587mm)
- [x] Optical lever is properly set. (The input beam is horizontal. The distance between the mirror surface and the fiber collimator is 1m.)
- [x] The mirror (including the FC tags) is not touching to anywhere.
- [x] The mirror is clining into the arm direction by 1/300.
- [x] Two wire breaker of the mirror at the both sides are at the same height

**References**
p.27 to 31 in https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument?docid=3830
p.15 in https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument?docid=4756

**Comment by YoshinoriFujii** [comment]
http://klog.icrr.u-tokyo.ac.jp/osl/?r=4989

> - We put the 90° prism on the RM and raised the OL to target it. The LED height was 92 mm above the breadboard, so the target was 112 mm.
> - We set the height to 267 mm above the trolley baseplate and the pitch to 1/300 down (achieved 110 mm, target 112 mm).
> - We did up the clamps to 2 N.m and 10 N.m as for the piano wires. There was no change in pitch of the RM.
> - We added the 3 poles for the bottom section of the security structure.
> - We put the bottom plate of the security structure on the optic trolley with a few cm of vertical spacers, and rolled it under the RM, letting it push out the RM trolley.
> - We lifted the bottom plate slightly and screwed it onto the poles.
> - We cut the wires and removed the winch system. The RM pitch was still unchanged.
> - We installed the TM OSEM cables and routed them up to the IM.
> - We located the #357 ring and #358 poles for the section of the security structure that supports the BF. We brought the poles into the cleanbooth and parked the ring outside for craning in tomorrow.
