### ISSUE TITLE
Clamp TM & RM wires

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/SR3_installation#12]
### TODO
- [x] Clamp TM and RM wires

### checklist
- [x] The wires are on the positioning plates.
- [x] The RM and mirror are protected with EQ stop screws and RM base
- [x] The clamping plates are fixed with proper force.
  - [x] using settings of ~5~ 2 N.m for the primary clamps
  - [x] ~20~ 10 N.m for the secondary.
- [x] The wire status was checked by loosening the winch.

**References**
p.15 in https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument?docid=4756
p.31 to 32 in https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument?docid=3830

**Comment by YoshinoriFujii** [comment]
http://klog.icrr.u-tokyo.ac.jp/osl/?r=4857

> We double-checked the OL level and the optic pitch. The OL input beam was aimed down by about 2 mm, so we raised it. The return beam was then at 77 mm, consistend with 73 mm yesterday.
> We made a number of small pitch adjustments (see paper log) and relaxed the system between, until we got the pitch to 59 mm (target 58 mm).
> We borrowed a torque wrench and practised on one of the M6 screws holding the trolley system to the optical table. We settled on **_5 N.m and 20 N.m_** as suitable torque values for the primary and secondary clamps, because they were similar in feel to what we had used for the BS and SR2. **`This was the main reason of the wire break.`**
> We tightened the primary prism screws to 5 N.m with a torque wrench and the pitch was almost unchanged, at 63 mm.
> We tightened the secondary prism screws to 20 N.m, and the pitch was 61 mm (target 58 mm).
> We placed a 90° prism on top of the RM and raised the OL to  target it.
> The LED was 86 mm above the breadboard, so the new target to give the RM the same pitch as the optic was 106 mm.
> We raised the RM by about 1 mm with the winches to get the wire breakers at 267 mm above the trolley baseplate, and set the pitch.
> The RM winch system was much more responsive than that for the optic, and we soon got 104 mm on the OL.
> We added the clamp blocks loosely and located the wires in the notches. The pitch was unchanged at 104 mm (target 106 mm).
> We tightened the primary clamp on the -X side to 5 N.m.
> However while tightening the clamp on the +X side, the tungsten wire on the +Y side broke immediately below the clamp.
> The +Y side of the RM fell a few mm onto the lip of the RM trolley (see photo) but there was no damage to the optic or magnets.
> The optic wires did not break but may have suffered greater than usual strain due to taking some share of the weight of the RM.
> There is a splinter of wire about 2 mm long coming down from the clamp (but unfortunately I was not able to get a good photo of it in situ). Apparently a crack started in the clamp and descended diagonally.
> We did up all the RM EQ stops until they touched, to continue to protect the magnets.
> After consulting with Aso-san, we raised the trolley to support the RM and get it back to nominal height and pitch.
> We locked the RM to its trolley, released the EQ stops holding the optic (but left them very close) and left the optic hanging overnight. If it remains hanging, we will remove the RM and optic by the reverse of the usual installation method, and then rehang them with fresh wire. Otherwise we will need a Plan B to get the optic out of the RM safely.
>

**Comment by YoshinoriFujii** [comment]
http://klog.icrr.u-tokyo.ac.jp/osl/?r=4970

> - We inspected the primary clamps for the tungsten wire.
>   - Clamp set No1, used on the -T (+X) side of the IM, was where the tungsten wire broke. (The break was on the right side looking towards the IM from +X.) The outer clamp piece had two scars from the wires, with the broken wire having cut deeper. (This probably means the clamp piece was not screwed on symmetrically, but could be because the second screw had not been fully tightened - need to check with Tanioka-kun.)
>   - Clamp set No2 (+T) had been tightened to 5 N.m on both sides by Mark with considerably attention to evenness and had two very similar scars. The wire on the right had been visibly crushed and was alarmingly bendable at the thin point, so it had probably been on the point of failure. 
>   - `Clearly 5 N.m is considerably too much` for the lower clamps for the tungsten.
> - None of the secondary clamps for the tungsten wire had beeen tightened at all, so there was nothing interesting  to inspect.
> - We inspected the primary clamps for the piano wire.
>   - Despite the much higher torque spec used (20 N.m), there was less scarring because the force is distributed over a much longer length.
>   -  The scars on the inner clamp piece (part of the main clamp block) were quite faint for both clamp sets. We can reuse them.
>   - The wires showed very slight signs of crushing and had a slight bend at the point where they emerged from the clamps, but were not obviously weak.
> We inspected the secondary clamps for the piano wire.
> There were deep symmetrical scars in the outer clamp pieces, but they are not grooved or otherwise special, so we can reuse them by turning them over.
> The inner clamp pieces (also part of the main clamp blocks) were very lightly scarred and can be reused.
> - We inspected all the clamp screws and found no signs of damage.
> - We decided to try again using considerably reduced torque specifications:
>   - **`2 N.m of torque for the primary clamp (down from 5 N.m).`** This is 2/3 of the rating of the M5 screws.
>   - **`10 N.m for the secondary clamps (down from 20 N.m).`** This is about 80% of the LIGO recommendation for Ag-plated 1/4-20 screws (comparable to M6).
> - We removed all the old wire from the winches and prepared to rehang the optic.
> - We set up the two laser levels we had been using, a Tajima and a Hitachi, to set the optic height, but then on a hunch, we decided to test them. As we suspected, the beams were not very level in the direction away from the tripods: the beam of the Tajima rose 4 mm relative to the floor over 7 m, and the Hitachi dropped 20 mm. We need to remember not to use the laser level to compare heights at different distances from the tripod.
> - We reinstalled the clamp sets on the IM and threaded 2 new piano wires.
> - We added a PEEK cable clamp piece as a spacer on top of the PEEK L-bracket at 6 o'clock on the lid of the mirror box, so the optic was supported at three points below (one L-bracket on the lid, two L-brackets on the baseplate).
> - We removed the two L-brackets at the top of the mirror box lid, so the optic was free to rise.
> - We checked the heights of the various items with the laser levels, now being careful to place the tripods so as to minimize variation in radial distance.
> - The optic was still at the target height of 267 mm above the trolley baseplate. However Fujii-kun noticed that the distance up to the IM was off by 3 mm.
> - Eventually we realized that when the assembly frame had been reconfigured after using it to test GAS filters, the IM crossbars had been put back 3 mm too high due to following Mirapro's assembly drawing rather than the assembly procedure. (The drawing does not reflect a 3 mm lowering of the table to allow the optic to approach the target height from below.)
> - We measured the IM crossbeam height and reset it to the target value of 1581 mm below the PI crossbeams, as for SR3.

**Comment by YoshinoriFujii** [comment]
http://klog.icrr.u-tokyo.ac.jp/osl/?r=4983

> - We checked the height of the IM crossbars above the optical table. It was 669 mm, which is consistent with Mirapro's diagram, but different from the assembly procedure which has it 3 mm lower to allow for the optic and RM to be raised during hanging. We decided to leave it for now.
> - We set up the OL at 3 m from the optic. The LED was 38 mm above the breadboard, making the target return height 38+2*3000/300 = 58 mm. 
> - We added the L-brackets at the top of the lid to give more protection.
> - We expanded the mirror box and adjusted the position of its trolley to give plenty of space on both sides, especially at the First Contact tab.
> - We realised that the stick-slip behaviour of the winches seen last time was from the clamp plates near the capstans, so we took them off and the pitch was much more responsive to winch adjustments. (In future we will still use them to control the wires temporarily during threading, but then take them back off.)
> - We used the winches to set the height of the prism to 267 mm ab ove the trolley baseplate, and the pitch to 1/300 down (target 58 mm, achieved 57 mm).
> - We tightened the primary clamps to 2 N.m and the secondary to 10 N.m (down from 5 N.m and 20 N.m last time). The OL barely changed at 59 mm (target 58 mm).
> - We brought in the RM on the trolley, attached the front ring and brought the EQ stops close but not touching..
> - We relaxed the optic wires using the EQ stops at the bottom of the RM (3/4 turn up from just touching, then back). The OL barely changed at 57 mm (target 58 mm).
> - We threaded two tungsen wires.
> - We unlocked the RM from the trolley and suspended it.
> - We set the height and pitch roughly but then ran out of time, so we raised the RM trolley to support the RM and locked the RM overnight.
