### ISSUE TITLE
Disassemble TM from RM

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/SR3_installation#14]
### TODO & checklist
- [ ] check how to use the disassembly jig
  - [ ] ask to Shoda-san!!!!
- [ ] get people (like 3 persons?) 
- [ ] find it near the PR3 booth

**References**
https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument?docid=6132

**Comment by YoshinoriFujii** [comment]
The disassembly jig was not used this time. The SR3 optic was packed inside the mirror box without the jig.
