### ISSUE TITLE
Insert & hang RM

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/SR3_installation#15]
### TODO
- [x] Insert the RM
- [x] Hang and align the RM

### checklist
9. Insert the RM
- [x] The RM is assembled.
- [x] EQ stop is not inserted too much.
- [ ] The height of the RM is adjusted with TM’s and RM’s wire breakers.
- [ ] All the OSEMs are not touching.
- [ ] Mirror is fixed by the EQ stop screws.
- [ ] The RM slider is fixed by the screw.

10. Hang and align the RM
- [ ] Wires are set pallallely around the RM
- [ ] Guide clamps are set but not fixed yet
-  ~OSEM cables are assembled and the signals are checked~
-  ~All the OSEMs are not touching~

**References**
https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument?docid=4756

**Comment by YoshinoriFujii** [comment]
see #11 or http://klog.icrr.u-tokyo.ac.jp/osl/?r=4989

**Comment by YoshinoriFujii** [comment]
We should watch the torque!

> - We decided to try again using considerably reduced torque specifications:
>   - 2 N.m of torque for the primary clamp (down from 5 N.m). This is 2/3 of the rating of the M5 screws.
>   - 10 N.m for the secondary clamps (down from 20 N.m). This is about 80% of the LIGO recommendation for Ag-plated 1/4-20 screws (comparable to M6).
