### ISSUE TITLE
Install EQ stop for BF

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/SR3_installation#19]
### TODO
- [x] Install assembly frame crossbars for under BF
- [x] Install EQ structure parts up to ring under BF
  - [ ] For each [1] rod, insert a (1) screw through the hole from underneath and into the end of
the rod. 
  - [ ] Tighten gently for now not be galled.
  - [ ] Crane the ring onto the top of the rods and secure with 4 more (2) screws. 
  - [ ] Tighten all 8 screws firmly.
  - [ ] Install 3 [3] stops, securing each with 2 x [2] screws from underneath through the ring.
  - [ ] In each of the stops, install a (4) stop screw with a (3) lock nut on the outside.
- [x] Install pushers and jacks at ring under BF

### Checklist
Install assembly frame crossbars for under BF
- [ ] the height from the top side of the IM crossbars to the underside of the BF crossbars, is 443 mm?

Install EQ structure parts up to ring under BF
- [ ] The four holes for the [1] rods in the ring under the IM, which are at 12, 3, 6 and 9
o’clock as viewed looking in the –X direction?
- [ ] Pick the ring up with the crane; viewed looking towards –X, the roundcornered
rectangular hole is square in X and Y, and there are tabs at 5:30, 9:30 and 1:30?

Install pushers and jacks at ring under BF
- [ ] The pointy pushers on the –Y side?
- [ ] The cup pushers on the +Y side.

**References**  
p.25 https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument?docid=4235
[1] https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument?docid=5124

**Comment by YoshinoriFujii** [comment]
http://klog.icrr.u-tokyo.ac.jp/osl/?r=4994

> - We installed 4 x #358 poles and craned in 1 x #357 disk to build up the security structure to below the BF.
> - We moved the large NB-03 jacks from the PI level up to the top level and craned in the load gauge adapter.
> - We suspended the chain block, load gauge and maraging rod adapter from the load gauge adapter.
> - We prepared the IM for weighing the IM/... section: 
>   - We replaced the screws and cable clamps that had been removed to install the winch system.
>   - We replaced the vertical IM flags (**`with the one with S polarity in the V1 position and N for V2 and V3`**.
>   - We added the ballast masses for the top of the IM according to the mass budget.
>   - We still need to add the BF-IM maraging rod and flying saucer cable clamp.
> - We paused work on the SR3 assembly and started on disassembling the PIs with cracked blades.
