### ISSUE TITLE
Install BF

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/SR3_installation#20]
### TODO
- [ ] Crane in BF
- [ ] Set height and level of BF

### checklist
Crane in BF
- [ ] Stand on the +X side of it and rotate it so that the triangle of IRM support rod holders is
pointing toward you and the screws for the fishing rod are at 10 o’clock. `->"+X side??"`
- [ ] When the BF is about to touch down, guide the two screws above the cup-head pushrods into the cups.

Set height and level of BF
- [ ] The jacks are adjisted until the BF is level according to a bubble level?
- [ ] there is a 38 mm gap from the top of the ring to the underside of the BF?

**Comment by YoshinoriFujii** [comment]
http://klog.icrr.u-tokyo.ac.jp/osl/?r=5019

> - We craned in the SR3 BF, set it to be 38 mm above the BF ring using the jacks, and removed the cap.
> - We checked the height of the receptacles for the rods supporting the IRM - they had already been set to the correct height (protruding 20 mm above the baseplate on top).
> - We installed the IRM rods (3 of No336) and the top plate of the IRM.
> - We installed the BF-IM maraging rod (1 of No335) with the flying saucer cable clamp about 2/3 of the way up. We used a sheet of foil with a small central hole for the rod to prevent the collets falling into the IM in case they were dropped while they were being inserted in the neck of the cable clamp. We did not hook the rod at the bottom yet.

**Comment by YoshinoriFujii** [comment]
http://klog.icrr.u-tokyo.ac.jp/osl/?r=5026

> - We tried hooking the IM to the BF but found the rod would not take up tension even with the BF raised to the maximum height on the jacks.
> - Aftyer a while, Hirata-san remembered that the height of the receptacle on the IM had been disturbed when we used the bottom end of it to hold the plumb bob for centering the the optical table.
> - `We reset the receptacle to stick out the prescribed amount of 27.4 mm below the bottom of the IM and were then able to suspend the IM, with the keystone locked to being with.` **`>?`**
> - At first the IM was low on the -L, +T corner, so we moved some of the smaller masses on the top of the IM to the +L,-T corner. The roll component of this imbalance is probably due to the thick side of the wedge being on the +T side, but we are not sure about the cause of the pitch imbalance.
> - Since we were obviously within easy tuning range of a good state, we immobilized the IM and spent some time routing cables. We got all the TM OSEM and IM pico cables routed through cable clamps on the top of the IM and the flying saucer cable clamp.
> - We released the IM and tweaked the pitch and roll a bit more.
> - We then released the BF keystone and found the IM/... section was slightly too heavy. This was not unexpected because the measured weight was 53.3 kg (klog 5008), whereas the load capacity of the BF was 53.17 kg (klog 4644).
> - **`We removed 215 g (4 medium mass plates, 1 thin mass plates) and got the BF keystone to sit at close to the target of 65.5 mm.`** The final trim mass configuration was
>   - +L,+T: 1 large block, 1 small plate.
>   - -L,+T: 1 large block.
>   - -L,-T: 1 large block, 1 medium plate.
>   - +L,-T: 1 large block, 3 medium plates, 2 small plates.
> - We immobilized the IM for the night. We will refine the pitch/roll/height tuning tomorrow.

**Comment by YoshinoriFujii** [comment]
Watch the rotation angle of the EQ ring for BF
http://klog.icrr.u-tokyo.ac.jp/osl/?r=5182
