### ISSUE TITLE
task list on the week of 2018-May-21th

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/SR3_installation#24]
http://gwwiki.icrr.u-tokyo.ac.jp/JGWwiki/KAGRA/Subgroups/VIS/TypeB/Minutes  

**participants:**  
Mark / Enzo / Kozu / Hirata-san / Yoshinori 

- [ ] Install IRM sides, and IM OSEMs.
- [ ] Center IM OSEMs (in/out and laterally)
- [ ] Route all cables to underneath BF.
- [ ] Add BF internal ballast mass.
- [ ] Add BF cap.

how do we parallelize?
