### ISSUE TITLE
cabling around BF

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/SR3_installation#25]
#### TODO
- [X] Remove BF cap with crane
- [x] Wire up
  - [X] BF yaw pico
  - [X] BF fishing rod stepper
  - [X] BF GAS LVDT

**References**
p.27 to 30 in https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument?docid=4235

**Comment by YoshinoriFujii** [comment]
http://klog.icrr.u-tokyo.ac.jp/osl/?r=5035
