### ISSUE TITLE
Install IRM top plate

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/SR3_installation#26]
### TODO
- [X] Route IM cables through IRM top plate up to BF
- [X] Adjust IRM rod holders
- [X] Suspend IM top plate with rods from BF

**Comment by YoshinoriFujii** [comment]
http://klog.icrr.u-tokyo.ac.jp/osl/?r=5019

> With Hirata-san, Enzo and Kozu-kun.
> 
> Today:
> 
> - We helped Takahashi-san characterize the prototype replacement F0 blades.
> - We dismantled most of the testing setup but left the prototype blades in the filter (#3).
> - We craned in the SR3 BF, set it to be 38 mm above the BF ring using the jacks, and removed the cap.
> - We checked the height of the receptacles for the rods supporting the IRM - they had already been set to the correct height (protruding 20 mm above the baseplate on top).
> - We installed the IRM rods (3 of #336) and the top plate of the IRM.
> - We installed the BF-IM maraging rod (1 of #335) with the flying saucer cable clamp about 2/3 of the way up. We used a sheet of foil with a small central hole for the rod to prevent the collets falling into the IM in case they were dropped while they were being inserted in the neck of the cable clamp. We did not hook the rod at the bottom yet.
