### ISSUE TITLE
hang & balance IM

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/SR3_installation#27]
### TODO
- [X] Hook IM to BF
- [X] Remove security bar between IM and RM
- [X] Raise BF with jacks, test payload weight match
- [X] balance IM

**References**
- p.32 in https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument?docid=4235

**Comment by YoshinoriFujii** [comment]
http://klog.icrr.u-tokyo.ac.jp/osl/?r=5019

http://klog.icrr.u-tokyo.ac.jp/osl/?r=5026

http://klog.icrr.u-tokyo.ac.jp/osl/?r=5035

> - We adjusted trim mass on the IM to get the pitch to 1/300 (per the OL), the roll to level (per the bubble level) and the BF keystone height to 65.5 mm. See paper log book (in NAOJGW Google Photos) for details.
