### ISSUE TITLE
Construct SUMCON model

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/SR3_installation#3]
## Purpose
For a reference of the SR3 assembly.  During the assembly and installation, This model is based on CAD parameters. **_So, this model will be updated after the assembly has completed, by  using the actual parameters._**

## TODO
- [ ] Construct a SUMCON model for SR3 assembly
- [ ] Upload onto SVN
- [ ] List up the resonant modes

### References
CAD model:
