### ISSUE TITLE
Install booth thermometer

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/SR3_installation#32]
### TODO
- [X] get from Kokeyama-san
- [X] install somewhere close to a tank
- [X] activate in online system

**Comment by YoshinoriFujii** [comment]
http://klog.icrr.u-tokyo.ac.jp/osl/?r=5075
