### ISSUE TITLE
F0 blade assembly

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/SR3_installation#38]
### TODO 
- [ ] assemble the blades
- [ ] tune the compression so that the resonant frequency becomes around 0.2-0.3 Hz.
- [ ] do calibration
- [ ] measure noise level

**Comment by YoshinoriFujii** [comment]
http://klog.icrr.u-tokyo.ac.jp/osl/?r=5200
