### ISSUE TITLE
Construct Simulink model

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/SR3_installation#4]
## Purpose
For a reference of the SR3 controls. **_This model will be updated after the assembly has completed, by  using the actual parameters._**

## TODO
- [ ] Import suspension model for SR3 from SUMCON
- [ ] Upload onto SVN
- [ ] build the system by mimicking the previous type-B models

### References
previous model:   
- typeB1_proto:  
https://granite.phys.s.u-tokyo.ac.jp/svn/LCGT/trunk/VIS/SuspensionControlModel/script/TypeB1Prototype/

**Comment by AyakaAShoda** [comment]
The model TypeBsimctrl.sxl can be used for all type-B suspensions. And it is done.
