### ISSUE TITLE
Set assembly & hanging frames

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/SR3_installation#5]
## TODO & checklist
- [x] reset assembly frame

1. Set the assembly frame and the hanging frame
- [x] The hanging frame is at the center of the assembly frame.
- [x] The optical table is leveled.
2. Fix the hanging frame and the set the sliders.
- [x] The hanging frame is fixed on the optical table.
- [x] Sliders are properly set and move smoothly.

### Reference
**Frame setting for SR:** https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument?docid=7053
**Installation:** p.9 in https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument?docid=4756

**Comment by YoshinoriFujii** [comment]
**Logs:**  
http://klog.icrr.u-tokyo.ac.jp/osl/?r=4763
http://klog.icrr.u-tokyo.ac.jp/osl/?r=4753
