### ISSUE TITLE
pico driver preparation

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/SR3_installation#6]
### TODO
- [X] check the ID numbers
- [ ] working test by joystick
- [ ] working test via MEDM

**Comment by YoshinoriFujii** [comment]
[k-log#4687](http://klog.icrr.u-tokyo.ac.jp/osl/?r=4687 "k-log#4687")  
SR3-IM (10.68.150.26) and SR3-BF (10.68.150.27):  
SN11460: S1808144 and SN11464: S1808145
