### ISSUE TITLE
OSEM calibration

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/SR3_installation#7]
### TODO & checklist
- [ ] calibrate the OSEMs for SR3
- [ ] write down the ID numbers of the OSEMs
- [ ] check if the signal is obtained properly
- [ ] compare with the previous ones.

**Comment by YoshinoriFujii** [comment]
http://klog.icrr.u-tokyo.ac.jp/osl/?r=4846

**IM-OSEM calibration**
[klog#4846](http://klog.icrr.u-tokyo.ac.jp/osl/?r=4846 "klog#4846")

| number#  | calibration factor [um/cnt] | linear range [cnt] | for which? | noise level |
|:---:|:---:|:---:|:---:|:---:|
| No#53  | 0.078991 | 1600-12500 | IM-V1 |  |
| No#54 | 0.079014 | 1480-12600 | IM-V2 |  |
| No#55 | 0.083248 | 1500-12000 | IM-V3 |  |
| No#56 | 0.074347 | 1390-14200 | IM-H1 |  |
| No#57 | 0.070756 | 1370-14700 | IM-H2 |  |
| No#58 | 0.088711 | 1450-11100 | IM-H3 |  |
