### ISSUE TITLE
IM installation

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/SR3_installation#9]
### checklist
- [ ] bring laser markers (2 of them)
- [ ] which position, the IM should be?

### TODO
3. Set IM EQ stop ring on the small frame  
- [ ] EQ stop is at the center of the hanging frame with alignment pins.
- [ ] EQ stop plate is fixed by the clamps.
4. Set the IM on the EQ stop ring
- [ ] IM is at the center of the EQ stop.
- [ ] IM is not tilting
- [ ] The distance between the IM and the base of the hanging frame is correct.
- [ ] The direction of the IM is OK.

**References**  
Installation procedure (TypeBp'):  
https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument?docid=4756
Installation procedure (BS test-hang):  
https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument?docid=4235

**Comment by YoshinoriFujii** [comment]
http://klog.icrr.u-tokyo.ac.jp/osl/?r=4763

> We double-checked and slightly improved the assembly frame vertical alignment in ±X from yesterday, and then aligned the frame in ±Y.
> We set the stops on the trolleys to put the "+" mark on each trolley in the center of the table when it was at its inward limit.
> `We installed and centered the interface bars on the IM crossbars.` **_-> how??_**
> `We installed the bars supporting the EQ stops for the IM.` **_-> which??_**
> `We installed the IM ring and attached the EQ stop bars.` **_-> clamped??_**
> We installed all but two of the EQ stop brackets on the EQ stop bars (leaving a gap to slide the IM in at one end).
> `We measured the thickness of the bottom ballast masses to be 12.5 mm and set the vertical screws which support the IM to stick out 22-12.5 = 9.5 mm above the EQ stop bars.` **_-> leveled??_**
> We installed `the last two EQ stops`. **_-> where??_**
> We installed the IM and adjusted it laterally so there was a 7 mm gap to the EQ stop brackets on the ±X sides and a 9 mm gap on the ±Y sides.
> We installed the PEEK cable clamps on the sides and top of the IM (they had been forgotten earlier).

**Comment by YoshinoriFujii** [comment]
http://klog.icrr.u-tokyo.ac.jp/osl/?r=4800

> We tidied the work area, and moved the mirror box, table and one of the KOACH filters to the +Y side of the AF. The table needs to go at 45° to fit next to the staircase, but `we should be able to lift the mirror box safely onto the optical table.`
`> We improved the centering of the IM in the EQ stops.` **_->how??_**
> In the X direction from the side of the IM to the inside of the EQ stop bracket is 7.5 mm, or 7.5+15=22.5 mm to the outside.
> In the Y direction from the side of the IM to the inside of the EQ stop bracket is 9.5 mm, or 9.5+12=21.5 mm to the outside.
> We realized that the IM was sitting too low because we had set the vertical screws to allow for the thickness of the ballast masses but the screws were not contacting the ballast masses! `We reset the screws to the full 22 mm.`
> `We leveled the IM using a bubble level and checked it with the laser level.`
> We used a plumb bob to check that the IM was centered over the optical table. It was already good in ±X but off by about 3 mm in -Y. `We decided to adjust the trolley stop screw rather than move the IM.`
> We removed the vertical IM flags, the cable clamps and 4 M5x15 screws from the top of the IM and attached the winch system using 4 M5x30 screws.

> `Enzo collected all the required in-vacuum cables for SR3.` **_-> more correctly, how?_**
> He also believes he has nearly all for SR2 but wants to double-check. He has not collected cables for the SRM yet, and many will need to be ordered.
